project_id = "tneqdznpappgpepkelav"

[functions.credit-referral]
verify_jwt = false

[functions.process-withdrawal]
verify_jwt = true

[functions.send-push-notification]
verify_jwt = true

[functions.verify-account]
verify_jwt = false
